# suppress future warnings generated by pandas
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
import os

SOURCE_DIRECTORY = "Data"

# list folders in the directory
types = os.listdir(SOURCE_DIRECTORY)

#create dataframe with columns img_no, type, img_path
df = pd.DataFrame(columns=['img_no', 'type', 'label', 'img_path'])
imgNo = 0
label = 1
for type in types:
    # list files in the folder
    path = os.path.join(SOURCE_DIRECTORY, type)
    files = os.listdir(path)

    # add rows to the dataframe
    for file in files:
        df = df.append({'img_no': imgNo, 'type': type, 'label':label, 'img_path': os.path.join(path, file)}, ignore_index=True)
        imgNo += 1
    label += 1

#set img_no as index
df.set_index('img_no', inplace=True)
df.to_csv("input.csv")
print(df)
